source = ~/.config/hypr/hypr_modules/monitors.conf
source = ~/.config/hypr/hypr_modules/my_programs.conf
source = ~/.config/hypr/hypr_modules/autostart.conf
source = ~/.config/hypr/hypr_modules/env_vars.conf
source = ~/.config/hypr/hypr_modules/appearance.conf
source = ~/.config/hypr/hypr_modules/input.conf
source = ~/.config/hypr/hypr_modules/keybindings.conf
source = ~/.config/hypr/hypr_modules/windows_and_workspaces.conf

# Force LibreOffice to act like a native GTK application, respecting Hyprland's tiling constraints immediately.
env = SAL_USE_VCLPLUGIN,gtk3
