##############################
### windows and workspaces ###
##############################

# windowrulev2 = suppressevent maximize, class:.*
# windowrule = tile 1, match:class ^(com-cburch-logisim-Main)$
follow_mouse = 1
mouse_refocus = false
# fix some dragging issues with xwayland
# windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
